# -*- coding: utf-8 -*-
"""Sistema de gestão de notas de alunos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R1U0B5PvhSeZRVUvC1B0-E-I0Qj_gJG
"""

# Sistema de gestão de notas de alunos

# Inserir as notas e armazenar em uma lista

notas = []
for i in range(5):   # repete 5 vezes
    nota = int(input("Digite a nota do aluno:"))
    notas.append(nota)  # adiciona a nota na lista


# Cálculo da Média

media = sum(notas) / len(notas)  # soma / quantidade de elementos

# Determinação da Situação

if media >= 7:
    situação = "Aprovado"
elif media < 7:
    situação = "Reprovado"

# Relatório Final

print("Notas cadastradas:", notas)
print("Média:", media)
print("Situação:", situação)